
// ACTIONS/MUTATIONS NAME CONSTANTS
export const SET_DIMENSIONS = 'SET_DIMENSIONS';
export const SET_SCROLL_HEIGHT = 'SET_SCROLL_HEIGHT';

// GETTERS NAME CONTANTS
export const GET_DIMENTSIONS = 'GET_DIMENTSIONS';
export const GET_LAPTOP_DIMENSIONS = 'GET_LAPTOP_DIMENSIONS';
export const GET_TABLET_DIMENSIONS = 'GET_TABLET_DIMENSIONS';
export const GET_MOBILE_DIMENSIONS = 'GET_MOBILE_DIMENSIONS';
export const GET_SCROLL_HEIGHT = 'GET_SCROLL_HEIGHT';